#!/bin/bash
#PBS -l nodes=1:ppn=16:dc2,walltime=6:00:00
#PBS -N app-testgradientflip
#PBS -V
#PBS -o stdout.$PBS_JOBID.log
#PBS -e stderr.$PBS_JOBID.log

[ $PBS_O_WORKDIR ] && cd $PBS_O_WORKDIR

if [ $ENV == "IUHPC" ]; then
	module load matlab
   	module load spm
fi

echo "starting matlab"
export MATLABPATH=$MATLABPATH:$SERVICE_DIR
matlab -nodisplay -nosplash -r main
if [ -s results.txt ];
then
	echo 0 > finished
else
	echo "output missing"
	echo 1 > finished
	exit 1
fi
